package it.gianmo.demonodo.ws.pa;

import it.gianmo.demonodo.ws.generated.*;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-28T20:39:22.520+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", name = "PagamentiTelematiciRT")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T20:39:22.520+02:00", comments = "Apache CXF 3.1.5")
public interface PagamentiTelematiciRT {

    @WebMethod(action = "paaInviaRT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRisposta")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "paaInviaRTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T20:39:22.520+02:00")
    public PaaInviaRTRisposta paaInviaRT(
        @WebParam(partName = "bodyrichiesta", name = "paaInviaRT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        PaaInviaRT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        IntestazionePPT header
    );

    @WebMethod(action = "paaInviaEsitoStorno")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRisposta")
    @RequestWrapper(localName = "paaInviaEsitoStorno", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaEsitoStorno")
    @ResponseWrapper(localName = "paaInviaEsitoStornoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaEsitoStornoRisposta")
    @WebResult(name = "paaInviaEsitoStornoRisposta", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T20:39:22.520+02:00")
    public TipoInviaEsitoStornoRisposta paaInviaEsitoStorno(
        @WebParam(name = "identificativoIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoIntermediarioPA,
        @WebParam(name = "identificativoStazioneIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoStazioneIntermediarioPA,
        @WebParam(name = "identificativoDominio", targetNamespace = "")
        java.lang.String identificativoDominio,
        @WebParam(name = "identificativoUnivocoVersamento", targetNamespace = "")
        java.lang.String identificativoUnivocoVersamento,
        @WebParam(name = "codiceContestoPagamento", targetNamespace = "")
        java.lang.String codiceContestoPagamento,
        @WebParam(name = "er", targetNamespace = "")
        byte[] er
    );
}
