package it.gianmo.demonodo.ws.pa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-28T21:00:48.403+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciRPTservice", 
                  wsdlLocation = "file:/C:/Users/Utente/IdeaProjects/DemoPrj/src/main/resources/wsdl/ec/NodoPerPa.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00", comments = "Apache CXF 3.1.5")
public class PagamentiTelematiciRPTservice extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTservice");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public final static QName PagamentiTelematiciRPTPort = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Utente/IdeaProjects/DemoPrj/src/main/resources/wsdl/ec/NodoPerPa.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciRPTservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Utente/IdeaProjects/DemoPrj/src/main/resources/wsdl/ec/NodoPerPa.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPTservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort() {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-05-28T21:00:48.403+02:00")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort(WebServiceFeature... features) {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class, features);
    }

}
